config/routes.rb
Rails.application.routes.draw do
  get 'oauths/ouath'

  get 'oauths/callback'

  root 'home#index', as: 'home_index'

  resources :decks do
    patch 'switch', on: :member
    resources :cards, only: [:new, :create]
  end

  resources :cards, only: [:index, :show, :edit, :update, :destroy] do
    patch 'review', on: :member
  end
  get 'card/back', to: 'cards#back'

  resources :users, only: [:new, :create, :edit, :update]

  get  'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'oauth/callback',  to: 'oauths#callback'
  get  'oauth/callback',  to: 'oauths#callback'
  get  'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
end

app/views/shared/_cards_table.html.erb
<% if @cards.any? %>

<table class="table table-hover">
  <thead>
    <tr>
      <th class="col-xs-2">Оригинал</th>
      <th class="col-xs-3">Перевод</th>
      <th class="col-xs-3 text-center">Дата пересмотра</th>
      <th class="col-xs-4"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @cards %>
  </tbody>
</table>

<% else %>

<p>Пока не добавлено ни одной карточки...</p>

<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, class: "alert alert-#{name} alert-dismissible fade in", role: "alert" do %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= msg %>
  <% end %>
<% end %>

app/views/shared/_oauth_buttons.html.erb
<div class="oauth-buttons">
  <%= link_to 'Продолжить с Google', auth_at_provider_path(provider: :google),
      class: 'btn btn-lg btn-default oauth-google' %>
</div>
<div class="or-row">
  <div class="or-line"></div>
  <div class="or-text">или</div>
  <div class="or-line"></div>
</div>