config/routes.rb
Rails.application.routes.draw do
  get 'oauths/ouath'

  get 'oauths/callback'

  root 'home#index', as: 'home_index'

  resources :decks do
    patch 'switch', on: :member
    resources :cards, only: [:new, :create]
  end

  resources :cards, only: [:index, :show, :edit, :update, :destroy] do
    patch 'review', on: :member
  end
  get 'card/back', to: 'cards#back'

  resources :users, only: [:new, :create, :edit, :update]

  get  'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'oauth/callback',  to: 'oauths#callback'
  get  'oauth/callback',  to: 'oauths#callback'
  get  'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
end

app/models/card.rb
class Card < ApplicationRecord
  attr_reader :picture_remote_url
  belongs_to :deck
  has_attached_file :picture, styles: { normal: "360x360#" },
                              default_style: :normal,
                              default_url: "/images/:class/:attachment/:style/missing.png"

  scope :for_review, -> { where "? >= review_date", Date.current }

  validates :original_text, :translated_text, :review_date, presence: true
  validates_attachment :picture, content_type: { content_type: /\Aimage/ },
                                 file_name: { matches: [/png\z/, /jpe?g\z/, /gif\z/] },
                                 size: { less_than: 5.megabytes }
  validate :can_not_be_equal

  before_validation :set_next_review_date, on: :create

  ACCEPT_DISTANCE = 2
  REVIEW_DATES = {
    0 => Time.current,
    1 => 12.hours.from_now,
    2 => 3.days.from_now,
    3 => 1.week.from_now,
    4 => 2.weeks.from_now,
    5 => 1.month.from_now
  }.freeze

  def distance_to(arg)
    DamerauLevenshtein.distance(arg, original_text)
  end

  def picture_remote_url=(url_value)
    return if url_value.blank?
    self.picture = URI.parse(url_value) unless picture.file?
    @picture_remote_url = url_value
  end

  def review(arg)
    result = right_translation?(arg)
    result ? success_review : fail_review
    set_next_review_date
    save
    result
  end

  private

  def can_not_be_equal
    if !(original_text.blank? || translated_text.blank?) &&
       translated_text.strip.casecmp?(original_text.strip)
      errors.add(:translated_text, "can't be equal to original text")
    end
  end

  def fail_review
    self.fail_reviews += 1
    return if success_reviews.zero? || !(fail_reviews % 3).zero?
    self.success_reviews -= 1
  end

  def success_review
    self.fail_reviews = 0
    return if success_reviews >= REVIEW_DATES.keys.max
    self.success_reviews += 1
  end

  def right_translation?(arg)
    distance_to(arg) <= ACCEPT_DISTANCE
  end

  def set_next_review_date
    self.review_date = REVIEW_DATES[success_reviews]
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  include DecksHelper

  before_action :require_login
  before_action :set_deck, only: [:new, :create]
  before_action :set_card, only: [:show, :edit, :update, :destroy, :review]
  before_action :require_original_text, only: [:review]
  before_action :store_card_back_location, only: [:index]

  def index
    @cards = current_user.cards
  end

  def show
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def back
    if session[:card_back_url]
      redirect_to session[:card_back_url]
    elsif current_deck
      redirect_to deck_url(current_deck)
    else
      redirect_to cards_url
    end
  end

  def create
    @card = @deck.cards.build(card_params)
    if @card.save
      redirect_to @card
    else
      render 'new'
    end
  end

  def update
    if @card.update(card_params)
      redirect_to @card
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to card_back_url
  end

  def review
    translation = params[:card][:original_text]
    if @card.review(translation)
      message = "Верно, правильное значение - #{@card.original_text}"
      typos_count = @card.distance_to(translation)
      message += ", у Вас опечатка - #{translation}" unless typos_count.zero?
      flash[:success] = message
    else
      flash[:danger] = "Не верно, правильное значение - #{@card.original_text}"
    end
    redirect_to home_index_url
  end

  private

  def require_original_text
    return if params[:card][:original_text].present?
    @card.errors.add(:original_text, :blank)
    render "home/index"
  end

  def set_deck
    @deck = current_user.decks.find_by(id: params[:deck_id])
  end

  def set_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :review_text,
                                 :picture, :picture_remote_url)
  end
end

app/views/cards/_buttons.html.erb
<div class="form-group">
  <div class="text-center">

    <%= link_to "Назад", card_back_path, class: "btn btn-default" %>

    <% if action_name != "show" %>
      <%= f.submit "Сохранить", class: "btn btn-warning" %>
    <% end %>

    <% if @card.persisted? %>
      <%= link_to "Удалить", @card, method: :delete, class: "btn btn-danger",
        data: { confirm: "Вы уверены?" } %>
    <% end %>

  </div>
</div>

app/views/cards/_card.html.erb
<tr class="card-row">
  <td><%= card.original_text %></td>
  <td><%= card.translated_text %></td>
  <td class="text-center"><%= format_date(card.review_date) %></td>

  <td class="text-right">
    <%= link_to "Показать", card, class: "btn btn-default" %>
    <%= link_to "Редактировать", edit_card_path(card), class: "btn btn-warning" %>
    <%= link_to "Удалить", card, method: :delete, class: "btn btn-danger",
      data: { confirm: "Вы уверены?" } %>
  </td>
</tr>

app/views/cards/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 card-form">

      <%= content_tag :h1, header %>

      <%= simple_form_for [@deck, @card], defaults: { required: false },
        html: { class: "form-horizontal" } do |f| %>

        <%= f.error_notification message: "Пожалуйста, устраните следующие ошибки:" %>

        <%= f.input :picture, as: :file, label: "Загрузить изображение" %>

        <%= f.input :picture_remote_url, label: "Или использовать URL" %>

        <%= f.input :original_text, label: "Оригинал" %>

        <%= f.input :translated_text, label: "Перевод" %>

        <% if @card.persisted? %>
          <%= f.input :review_date, label: "Дата пересмотра", icon: "glyphicon glyphicon-calendar" %>
        <% end %>

        <%= render "buttons", f: f %>

      <% end %>

    </div>
  </div>
</div>

app/views/cards/edit.html.erb
<%= render "form", header: "Редактировать карточку" %>

app/views/cards/index.html.erb
<h1>Флеш-карточки</h1>

<%= render "shared/cards_table" %>

app/views/cards/new.html.erb
<%= render "form", header: "Новая карточка" %>

app/views/cards/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 card-form">

      <h1>Флеш-карточка</h1>

      <%= simple_form_for @card, defaults: { required: false, as: :display },
        html: { class: "form-horizontal" },
        wrapper: :horizontal_form_static do |f| %>

        <%= image_tag @card.picture.url, alt: @card.translated_text,
            class: "card-picture"  %>

        <%= f.input :original_text, label: "Оригинал" %>

        <%= f.input :translated_text, label: "Перевод" %>

        <%= f.input :review_date, label: "Дата пересмотра" %>

        <%= render "buttons", f: f %>

      <% end %>

    </div>
  </div>
</div>