config/routes.rb
Rails.application.routes.draw do
  get 'oauths/ouath'

  get 'oauths/callback'

  root 'home#index', as: 'home_index'

  resources :decks do
    patch 'switch', on: :member
    resources :cards, only: [:new, :create]
  end

  resources :cards, only: [:index, :show, :edit, :update, :destroy] do
    patch 'review', on: :member
  end
  get 'card/back', to: 'cards#back'

  resources :users, only: [:new, :create, :edit, :update]

  get  'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'oauth/callback',  to: 'oauths#callback'
  get  'oauth/callback',  to: 'oauths#callback'
  get  'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy
  validates :name, presence: true
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :require_login
  before_action :set_deck, only: [:show, :edit, :update, :destroy, :switch]
  before_action :store_card_back_location, only: [:index, :show]

  def index
    @decks = current_user.decks
  end

  def show
    @cards = @deck.cards
  end

  def new
    @deck = Deck.new
  end

  def edit
  end

  def create
    @deck = current_user.decks.build(deck_params)
    if @deck.save
      redirect_to @deck
    else
      render 'new'
    end
  end

  def update
    if @deck.update(deck_params)
      redirect_to @deck
    else
      render 'edit'
    end
  end

  def destroy
    @deck.destroy
    redirect_to decks_path
  end

  def switch
    current_user.switch_deck(@deck)
    redirect_to decks_path
  end

  private

  def set_deck
    @deck = current_user.decks.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:name)
  end
end

app/helpers/decks_helper.rb
module DecksHelper
  def cards_for_review
    current_cards.for_review
  end

  def current_deck
    current_user.current_deck
  end

  def current_cards
    current_deck ? current_deck.cards : current_user.cards
  end
end

app/views/decks/_deck.html.erb
<li class="col-md-3 col-sm-6">
  <div class="thumbnail deck-item">

    <% if deck == current_deck %>
      <p class="current">Текущая</p>
    <% else %>
      <p class="non-current"></p>
    <% end %>

    <div class="caption">

      <h3><%= deck.name %></h3>

      <p><%= link_to "Карточек: #{deck.cards.count}", deck_path(deck), title: "Показать" %></p>
      <p><%= link_to "Добавить карточку", new_deck_card_path(deck) %></p>

      <div class="buttons">
        <% if deck == current_deck %>
          <%= link_to "Убрать",  switch_deck_path(deck), method: :patch, class: "btn btn-clear" %>
        <% else %>
          <%= link_to "Выбрать", switch_deck_path(deck), method: :patch, class: "btn btn-success" %>
        <% end %>
        <%= link_to "Поправить", edit_deck_path(deck), class: "btn btn-warning" %>
        <%= link_to "Удалить", deck, method: :delete, class: "btn btn-danger",
            data: { confirm: "Вы уверены?" } %>
      </div>
    </div>
  </div>
</li>

app/views/decks/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 card-form">

      <%= content_tag :h1, header %>

      <%= simple_form_for @deck, defaults: { required: false },
                                 html: { class: "form-horizontal" } do |f| %>

        <%= f.error_notification message: "Пожалуйста, устраните следующие ошибки:" %>

        <%= f.input :name, label: "Название колоды" %>

        <div class="form-group">
          <div class="text-center">

            <%= link_to "Назад", decks_path, class: "btn btn-default" %>

            <%= f.submit "Сохранить", class: "btn btn-warning" %>

            <% if @deck.persisted? %>
              <%= link_to "Удалить", @deck, method: :delete, class: "btn btn-danger",
                data: { confirm: "Вы уверены?" } %>
            <%end %>

          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/decks/edit.html.erb
<%= render "form", header: "Редактировать колоду" %>

app/views/decks/index.html.erb
<div class="deck-header clearfix">
  <h1 class="pull-left">Колоды карточек</h1>
  <div class="buttons pull-right">
    <%= link_to "Добавить колоду", new_deck_path, class: "btn btn-success" %>
  </div>
</div>

<ul class="deck-list">
  <%= render @decks %>
</ul>

app/views/decks/new.html.erb
<%= render "form", header: "Создать колоду" %>

app/views/decks/show.html.erb
<div class="deck-header clearfix">
  <h1 class="pull-left"><%= @deck.name %></h1>
  <div class="buttons pull-right">
    <%= link_to "Добавить карточку", new_deck_card_path(@deck), class: "btn btn-success" %>
    <%= link_to "Назад", decks_path, class: "btn btn-default" %>
  </div>
</div>

<%= render "shared/cards_table" %>