config/routes.rb
Rails.application.routes.draw do
  get 'oauths/ouath'

  get 'oauths/callback'

  root 'home#index', as: 'home_index'

  resources :decks do
    patch 'switch', on: :member
    resources :cards, only: [:new, :create]
  end

  resources :cards, only: [:index, :show, :edit, :update, :destroy] do
    patch 'review', on: :member
  end
  get 'card/back', to: 'cards#back'

  resources :users, only: [:new, :create, :edit, :update]

  get  'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'oauth/callback',  to: 'oauths#callback'
  get  'oauth/callback',  to: 'oauths#callback'
  get  'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Флэшкарточкер</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id="container">

      <header class="clearfix">
        <nav class="navbar navbar-default">
          <div class="container-fluid">

            <div class="navbar-header">
              <%= link_to "Флэшкарточкер", home_index_path, class: "navbar-brand" %>
            </div>

            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                  <li><%= link_to "Все карточки", cards_path %></li>
                  <li><%= link_to "Колоды", decks_path %></li>
                  <% if current_deck %>
                    <li><%= link_to "Добавить карточку", new_deck_card_path(current_deck) %></li>
                  <% end %>
                  <li class="dropdown">
                    <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                      Аккаунт <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Обновить", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li><%= link_to "Выйти", logout_path, method: "delete" %></li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Регистрация", signup_path %></li>
                  <li><%= link_to "Войти", login_path %></li>
                <% end %>
              </ul>
            </div>

          </div>
        </nav>
      </header>

      <section>
        <%= yield %>
      </section>

    </section>
  </body>
</html>